export enum ORDER_TYPE {
  MARKET = "MARKET",
  LIMIT = "LIMIT",
  STOP = "STOP",
}

export enum SIDE {
  BUY = "BUY",
  SELL = "SELL",
}

export enum ACTION {
  OPENING = "OPENING",
  CLOSING = "CLOSING",
}

export enum TIF {
  GTC = "GTC",
  DAY = "DAY",
  GTD = "GTD",
}

export enum ERROR {
  NO_SESSION = "NO_SESSION",

  // Session
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_ERROR = "LOGIN_ERROR",
  CSRF_NOT_FOUND = "CSRF_NOT_FOUND",
  CSRF_ERROR = "CSRF_ERROR",
  ACCOUNT_SWITCH_ERROR = "ACCOUNT_SWITCH_ERROR",

  // Market data
  NO_SUGGESTIONS = "NO_SUGGESTIONS",
  SUGGEST_ERROR = "SUGGEST_ERROR",
  NO_SYMBOL_INFO = "NO_SYMBOL_INFO",
  SYMBOL_INFO_ERROR = "SYMBOL_INFO_ERROR",
  INSTRUMENTS_TIMEOUT = "INSTRUMENTS_TIMEOUT",
  INSTRUMENTS_ERROR = "INSTRUMENTS_ERROR",
  LIMITS_TIMEOUT = "LIMITS_TIMEOUT",
  LIMITS_ERROR = "LIMITS_ERROR",
  OHLC_TIMEOUT = "OHLC_TIMEOUT",
  OHLC_ERROR = "OHLC_ERROR",

  // Trading
  ORDER_ERROR = "ORDER_ERROR",
  POSITION_CLOSE_ERROR = "POSITION_CLOSE_ERROR",

  // Account
  ACCOUNT_METRICS_TIMEOUT = "ACCOUNT_METRICS_TIMEOUT",
  ACCOUNT_METRICS_ERROR = "ACCOUNT_METRICS_ERROR",
  ACCOUNT_POSITIONS_TIMEOUT = "ACCOUNT_POSITIONS_TIMEOUT",
  ACCOUNT_POSITIONS_ERROR = "ACCOUNT_POSITIONS_ERROR",
  TRADE_JOURNAL_ERROR = "TRADE_JOURNAL_ERROR",

  // Analytics
  ASSESSMENTS_ERROR = "ASSESSMENTS_ERROR",
}

export enum WS_MESSAGE {
  ACCOUNT_METRICS = "ACCOUNT_METRICS",
  ACCOUNTS = "ACCOUNTS",
  AVAILABLE_WATCHLISTS = "AVAILABLE_WATCHLISTS",
  CHART_FEED_SUBTOPIC = "chartFeedSubtopic",
  INSTRUMENTS = "INSTRUMENTS",
  INSTRUMENT_METRICS = "INSTRUMENT_METRICS",
  LIMITS = "LIMITS",
  MESSAGE = "MESSAGE",
  ORDERS = "ORDERS",
  POSITIONS = "POSITIONS",
  POSITION_CASH_TRANSFERS = "POSITION_CASH_TRANSFERS",
  PRIVATE_LAYOUT_NAMES = "PRIVATE_LAYOUT_NAMES",
  SHARED_PROPERTIES_MESSAGE = "SHARED_PROPERTIES_MESSAGE",
  TRADE_STATUSES = "TRADE_STATUSES",
  USER_LOGIN_INFO = "USER_LOGIN_INFO",
}

export namespace WS_MESSAGE {
  export enum SUBTOPIC {
    BIG_CHART_COMPONENT = "BigChartComponentPresenter-4",
  }
}
