export enum ORDER_TYPE {
  MARKET = "MARKET",
  LIMIT = "LIMIT",
  STOP = "STOP",
}

export enum SIDE {
  BUY = "BUY",
  SELL = "SELL",
}

export enum ACTION {
  OPENING = "OPENING",
  CLOSING = "CLOSING",
}

export enum TIF {
  GTC = "GTC",
  DAY = "DAY",
  GTD = "GTD",
}

export enum WS_MESSAGE {
  ACCOUNTS = "ACCOUNTS",
  AVAILABLE_WATCHLISTS = "AVAILABLE_WATCHLISTS",
  MESSAGE = "MESSAGE",
  ORDERS = "ORDERS",
  POSITIONS = "POSITIONS",
  POSITION_CASH_TRANSFERS = "POSITION_CASH_TRANSFERS",
  PRIVATE_LAYOUT_NAMES = "PRIVATE_LAYOUT_NAMES",
  SHARED_PROPERTIES_MESSAGE = "SHARED_PROPERTIES_MESSAGE",
  USER_LOGIN_INFO = "USER_LOGIN_INFO",
}